services:
  postgres:
    image: postgres:15
    container_name: jobsboard-postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jobsboard
    ports:
      - "5432:5432"